//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT_Flow.App.Paginas.RRHH
{
    public partial class Colaboradores_Pagamento_Detalhe
    {
        protected global::System.Web.UI.UpdatePanel UpdGeral;
        protected global::System.Web.UI.WebControls.Label lblTituloPagina;
        protected global::System.Web.UI.WebControls.Label lblSubTituloPagina;
        protected global::TT_Flow.App.Controles.BreadCrumb BreadCrumb_Pagina;
        protected global::TT_Flow.App.Controles.MensagemPagina MensagemPagina;
        protected global::TT_Flow.App.Controles.PainelAtualizacao PainelAtualizacao;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnCabecalho;
        protected global::System.Web.UI.WebControls.HiddenField hddidPagamento;
        protected global::System.Web.UI.WebControls.HiddenField hddSomenteLeitura;
        protected global::System.Web.UI.WebControls.HiddenField hddItensPagamento;
        protected global::System.Web.UI.WebControls.HiddenField hddScrollY;
        protected global::System.Web.UI.WebControls.DropDownList ddlidTipo;
        protected global::System.Web.UI.WebControls.TextBox txtsDscTipo;
        protected global::System.Web.UI.WebControls.TextBox txtdtEmissao;
        protected global::System.Web.UI.WebControls.TextBox txtdtVencimento;
        protected global::System.Web.UI.WebControls.DropDownList ddlidEmpresa;
        protected global::System.Web.UI.WebControls.TextBox txtsDscEmpresa;
        protected global::System.Web.UI.WebControls.TextBox txtsSituacao;
        protected global::System.Web.UI.WebControls.TextBox txtsObservacao;
        protected global::System.Web.UI.WebControls.Panel pnItensPagamento;
        protected global::System.Web.UI.WebControls.Label lblResumoItens;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnRemoverSelecionados;
        protected global::System.Web.UI.WebControls.Button cmdRemoverSelecionados;
        protected global::System.Web.UI.WebControls.GridView gvItensPagamento;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl DIV_Filtro;
        protected global::System.Web.UI.WebControls.TextBox txtPesquisa;
        protected global::System.Web.UI.WebControls.DropDownList ddlidDepartamento;
        protected global::System.Web.UI.WebControls.DropDownList ddlsCBO;
        protected global::System.Web.UI.WebControls.DropDownList ddlidGHE;
        protected global::System.Web.UI.WebControls.DropDownList ddlidCargo;
        protected global::System.Web.UI.WebControls.DropDownList ddlidSupervisorDireto;
        protected global::System.Web.UI.WebControls.DropDownList ddlidTipoContrato;
        protected global::System.Web.UI.WebControls.DropDownList ddlidFuncao;
        protected global::System.Web.UI.WebControls.DropDownList ddlsSituacao;
        protected global::System.Web.UI.WebControls.Button cmdBuscarColaboradores;
        protected global::System.Web.UI.WebControls.Panel pnColaboradores;
        protected global::System.Web.UI.WebControls.Button cmdAdicionarSelecionados;
        protected global::System.Web.UI.WebControls.GridView gvColaboradores;
        protected global::System.Web.UI.WebControls.Button cmdSalvar;
    }
}
