//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo foi gerado por uma ferramenta.
//
//     As alteracoes feitas neste arquivo poderao causar comportamento incorreto e serao perdidas se
//     o codigo for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT_Flow.App.Controles
{
    public partial class IA_Widget
    {
        protected global::System.Web.UI.WebControls.HyperLink lnkPerguntarIA;
    }
}
