//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo foi gerado por uma ferramenta.
//
//     As alteracoes feitas neste arquivo poderao causar comportamento incorreto e serao perdidas se
//     o codigo for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT_Flow.App.Paginas.IA
{
    public partial class Uso
    {
        protected global::System.Web.UI.WebControls.Label lblTituloPagina;

        protected global::TT_Flow.App.Controles.BreadCrumb BreadCrumb_Pagina;

        protected global::TT_Flow.App.Controles.MensagemPagina MensagemPagina;

        protected global::System.Web.UI.WebControls.DropDownList ddlPeriodo;

        protected global::System.Web.UI.WebControls.Button cmdAtualizar;

        protected global::System.Web.UI.WebControls.Label lblCardConversas;

        protected global::System.Web.UI.WebControls.Label lblCardPerguntas;

        protected global::System.Web.UI.WebControls.Label lblCardRespostas;

        protected global::System.Web.UI.WebControls.Label lblCardTokensEntrada;

        protected global::System.Web.UI.WebControls.Label lblCardTokensSaida;

        protected global::System.Web.UI.WebControls.Label lblCardCusto;

        protected global::System.Web.UI.WebControls.Literal ltrResumoPerguntas;

        protected global::System.Web.UI.WebControls.Literal ltrResumoTokens;

        protected global::System.Web.UI.WebControls.GridView dtgvUsoUsuarios;

        protected global::System.Web.UI.WebControls.GridView dtgvUsoModelos;

        protected global::System.Web.UI.WebControls.Panel pnPrecos;

        protected global::System.Web.UI.WebControls.GridView dtgvPrecosModelos;

        protected global::System.Web.UI.WebControls.Label lblPrecosVazio;

        protected global::System.Web.UI.WebControls.DropDownList ddlModeloPreco;

        protected global::System.Web.UI.WebControls.TextBox txtPrecoModeloEntrada;

        protected global::System.Web.UI.WebControls.TextBox txtPrecoModeloSaida;

        protected global::System.Web.UI.WebControls.Button cmdSalvarPrecoModelo;

        protected global::System.Web.UI.WebControls.TextBox txtPrecoEntrada;

        protected global::System.Web.UI.WebControls.TextBox txtPrecoSaida;

        protected global::System.Web.UI.WebControls.Button cmdSalvarPrecos;
    }
}
